@Tags(['rust'])
library;

import 'dart:io';

import 'package:flutter/services.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:choke/services/key_management/key_manager.dart';
import 'package:choke/services/nostr/crypto/nostr_crypto.dart';
import 'package:choke/services/nostr/crypto/nostr_tools_crypto.dart';
import 'package:choke/services/nostr/crypto/rust_nostr_crypto.dart';
import 'package:choke/src/rust/frb_generated.dart';

/// The upgrade this phase actually ships: an install whose keys were generated
/// by the old backend now runs on the new one.
///
/// The user's identity is the key sitting in secure storage, and it is *not*
/// migrated — it is re-read. So the only thing that can go wrong is the new
/// backend deriving something different from those same bytes. That is what
/// these tests forbid, and it is why the Phase 4 QA item "an existing install
/// keeps its npub" is checked by a machine rather than by someone's memory of
/// what their npub looked like yesterday.
///
///   cargo build --manifest-path rust/Cargo.toml
///   flutter test --tags rust
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  final libraryPath = _findNativeLibrary();
  final skip = libraryPath == null
      ? 'native library not built — run: cargo build --manifest-path rust/Cargo.toml'
      : null;

  group('crypto backend swap', skip: skip, () {
    late Map<String, String> storage;

    setUpAll(() async {
      await RustLib.init(externalLibrary: ExternalLibrary.open(libraryPath!));
    });

    tearDownAll(() => RustLib.dispose());

    setUp(() {
      storage = {};
      TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
          .setMockMethodCallHandler(
        const MethodChannel('plugins.it_nomads.com/flutter_secure_storage'),
        (call) async {
          final args = (call.arguments as Map?)?.cast<String, dynamic>() ?? {};
          final key = args['key'] as String?;
          switch (call.method) {
            case 'write':
              storage[key!] = args['value'] as String;
              return null;
            case 'read':
              return storage[key];
            case 'delete':
              storage.remove(key);
              return null;
            case 'readAll':
              return storage;
            case 'deleteAll':
              storage.clear();
              return null;
            case 'containsKey':
              return storage.containsKey(key);
            default:
              return null;
          }
        },
      );
    });

    KeyManager managerOn(NostrCrypto crypto) => KeyManager(
          secureStorage: const FlutterSecureStorage(),
          crypto: crypto,
        );

    test('an install created on the old backend keeps its npub on the new one',
        () async {
      // Arrange — yesterday's app: keys generated by nostr_tools
      final before = managerOn(NostrToolsCrypto());
      await before.initialize();
      final npubBefore = await before.getNpub();
      final nsecBefore = await before.getNsec();
      final privateKeyBefore = await before.getPrivateKeyHex();

      // Act — today's app: same secure storage, Rust backend
      final after = managerOn(const RustNostrCrypto());
      await after.initialize();

      // Assert — the identity the user shows the world does not move. A
      // mismatch here would strand every existing install: their matches would
      // start publishing from an npub nobody is following.
      expect(await after.getNpub(), npubBefore);
      expect(await after.getNsec(), nsecBefore);
      expect(await after.getPrivateKeyHex(), privateKeyBefore);
    });

    test('rolling back to the old backend keeps the npub too', () async {
      // Arrange — an install created on Rust
      final onRust = managerOn(const RustNostrCrypto());
      await onRust.initialize();
      final npub = await onRust.getNpub();

      // Act — the flag is flipped back (the documented rollback)
      final rolledBack = managerOn(NostrToolsCrypto());
      await rolledBack.initialize();

      // Assert — a rollback that stranded the user would be no rollback at all
      expect(await rolledBack.getNpub(), npub);
    });

    test('an nsec imported on one backend is readable on the other', () async {
      // Arrange — the user restores a backup on the old app…
      const nsec =
          'nsec1vl029mgpspedva04g90vltkh6fvh240zqtv9k0t9af8935ke9laqsnlfe5';
      final legacy = managerOn(NostrToolsCrypto());
      await legacy.initialize();
      await legacy.importFromNsec(nsec);
      final npub = await legacy.getNpub();

      // Act — …and then upgrades
      final rust = managerOn(const RustNostrCrypto());
      await rust.initialize();

      // Assert
      expect(await rust.getNsec(), nsec);
      expect(await rust.getNpub(), npub);
    });

    test('a public key stored wrong is repaired identically by both backends',
        () async {
      // Arrange — a corrupted install: the stored pubkey does not belong to the
      // stored private key. KeyManager re-derives rather than trusting it.
      final legacy = managerOn(NostrToolsCrypto());
      await legacy.initialize();
      final privateKey = storage['nostr_private_key']!;
      storage['nostr_public_key'] = 'deadbeef' * 8;

      // Act
      final rust = managerOn(const RustNostrCrypto());
      await rust.initialize();

      // Assert — the repair lands on the same key either backend would derive
      expect(
        await rust.getPublicKeyHex(),
        NostrToolsCrypto().getPublicKey(privateKey),
      );
    });
  });
}

/// Where `cargo build` leaves the crate, or null if it has not been built.
String? _findNativeLibrary() {
  final name = Platform.isMacOS
      ? 'librust_lib_choke.dylib'
      : Platform.isWindows
          ? 'rust_lib_choke.dll'
          : 'librust_lib_choke.so';

  for (final profile in ['debug', 'release']) {
    final path = 'rust/target/$profile/$name';
    if (File(path).existsSync()) return path;
  }
  return null;
}
