// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Whether `event_json` is a well-formed Nostr event whose id and Schnorr
/// signature both check out.
///
/// Returns `Err` only when the input does not parse as an event; an event
/// that parses but fails verification is `Ok(false)`.
bool verifyEvent({required String eventJson}) =>
    RustLib.instance.api.crateApiCryptoVerifyEvent(eventJson: eventJson);
