// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'crypto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `client`, `status_tx`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Register a relay with the pool and dial it.
Future<void> relayAdd({required String url}) =>
    RustLib.instance.api.crateApiRelayRelayAdd(url: url);

Future<void> relayRemove({required String url}) =>
    RustLib.instance.api.crateApiRelayRelayRemove(url: url);

/// Connect every registered relay.
Future<void> relayConnect() => RustLib.instance.api.crateApiRelayRelayConnect();

Future<void> relayDisconnect() =>
    RustLib.instance.api.crateApiRelayRelayDisconnect();

/// Drop every socket and dial again.
///
/// The pool reconnects on its own eventually, but "eventually" is measured in
/// TCP timeouts. When the app resumes we already know the sockets are suspect —
/// the OS kills them without a close frame — and the referee's next tap must
/// not wait for the kernel to work that out.
Future<void> relayReconnectAll() =>
    RustLib.instance.api.crateApiRelayRelayReconnectAll();

/// Publish to **one** relay and report that relay's verdict.
///
/// `true` = this relay accepted it. `false` = it rejected it (rate limits, an
/// invalid event, policy). `Err` = we never heard from it at all.
///
/// Publishing one relay at a time, rather than fanning out inside the pool, is
/// deliberate: the caller's convergence bookkeeping is per relay, and a
/// pool-level "it worked" would flatten exactly the distinction that matters.
Future<bool> relayPublish(
        {required String url, required SignedEventData event}) =>
    RustLib.instance.api.crateApiRelayRelayPublish(url: url, event: event);

Future<void> relaySubscribe(
        {required String subscriptionId, required FilterData filter}) =>
    RustLib.instance.api.crateApiRelayRelaySubscribe(
        subscriptionId: subscriptionId, filter: filter);

Future<void> relayUnsubscribe({required String subscriptionId}) =>
    RustLib.instance.api
        .crateApiRelayRelayUnsubscribe(subscriptionId: subscriptionId);

/// Every registered relay, connected or not. Convergence is measured against
/// this list, so it must not quietly drop the relays that are currently down.
Future<List<String>> relayUrls() =>
    RustLib.instance.api.crateApiRelayRelayUrls();

/// The subset currently connected.
Future<List<String>> relayConnected() =>
    RustLib.instance.api.crateApiRelayRelayConnected();

/// Every event arriving from any relay.
///
/// Deliberately built on the pool's raw `Message` notifications rather than its
/// de-duplicated `Event` ones: those drop events this client sent itself, and
/// events it has seen before. The app needs the relay's echo of its own matches
/// — that echo is how a second device learns the score. Filtering (NIP-40
/// expiry, addressable replacement) is the caller's job either way.
Stream<SignedEventData> relayEventStream() =>
    RustLib.instance.api.crateApiRelayRelayEventStream();

/// Fires whenever a relay goes up or down.
///
/// A connection is the caller's cue to push state that relay missed while it
/// was away; a disconnection is its cue to stop counting on it.
Stream<RelayStatusData> relayStatusStream() =>
    RustLib.instance.api.crateApiRelayRelayStatusStream();

/// A NIP-01 `REQ` filter. Empty vectors and `None` mean "unconstrained" — the
/// same shape the Dart `Filter` has, so the mapping stays honest.
class FilterData {
  final Uint16List kinds;
  final List<String> authors;
  final List<String> ids;
  final PlatformInt64? since;
  final PlatformInt64? until;
  final int? limit;

  const FilterData({
    required this.kinds,
    required this.authors,
    required this.ids,
    this.since,
    this.until,
    this.limit,
  });

  @override
  int get hashCode =>
      kinds.hashCode ^
      authors.hashCode ^
      ids.hashCode ^
      since.hashCode ^
      until.hashCode ^
      limit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FilterData &&
          runtimeType == other.runtimeType &&
          kinds == other.kinds &&
          authors == other.authors &&
          ids == other.ids &&
          since == other.since &&
          until == other.until &&
          limit == other.limit;
}

/// A relay went up, or went down.
class RelayStatusData {
  final String url;
  final bool connected;

  const RelayStatusData({
    required this.url,
    required this.connected,
  });

  @override
  int get hashCode => url.hashCode ^ connected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelayStatusData &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          connected == other.connected;
}
